#pragma once

#define MY_ENGINE_PRAGMA(x)				__pragma(x)

#define MY_ENGINE_SUPPRESS_WARNING_PUSH MY_ENGINE_PRAGMA(warning(push))

#define MY_ENGINE_SUPPRESS_WARNING_POP MY_ENGINE_PRAGMA(warning(pop))

#define MY_ENGINE_WARNING(w) MY_ENGINE_PRAGMA(warning(disable: w))

#define MY_ENGINE_SUPPRESS_WARNING	\
MY_ENGINE_WARNING(4061)				\
MY_ENGINE_WARNING(4062)				\
MY_ENGINE_WARNING(4127)				\
MY_ENGINE_WARNING(4263)				\
MY_ENGINE_WARNING(4264)				\
MY_ENGINE_WARNING(4266)				\
MY_ENGINE_WARNING(4265)				\
MY_ENGINE_WARNING(4365)				\
MY_ENGINE_WARNING(4514)				\
MY_ENGINE_WARNING(4619)				\
MY_ENGINE_WARNING(4623)				\
MY_ENGINE_WARNING(4625)				\
MY_ENGINE_WARNING(4626)				\
MY_ENGINE_WARNING(4668)				\
MY_ENGINE_WARNING(4702)				\
MY_ENGINE_WARNING(4710)				\
MY_ENGINE_WARNING(4711)				\
MY_ENGINE_WARNING(4777)				\
MY_ENGINE_WARNING(4820)				\
MY_ENGINE_WARNING(5027)				\
MY_ENGINE_WARNING(5039)				\
MY_ENGINE_WARNING(5204)				\
MY_ENGINE_WARNING(5219)				\
MY_ENGINE_WARNING(5220)				\
MY_ENGINE_WARNING(5246)				\
MY_ENGINE_WARNING(5266)				\
MY_ENGINE_WARNING(5267)

#define MY_ENGINE_SUPPRESS_WARNINGS_BEGIN	\
MY_ENGINE_SUPPRESS_WARNING_PUSH				\
MY_ENGINE_SUPPRESS_WARNING					\

#define MY_ENGINE_SUPPRESS_WARNINGS_END \
MY_ENGINE_SUPPRESS_WARNING_POP

#define MY_ENGINE_UTILITY_NAMESPACE_BEGIN	\
namespace MY_ENGINEUtility					\
{										\


#define MY_ENGINE_UTILITY_NAMESPACE_END	\
}									\
